=== openstreetmap/id-tagging-schema/schemas/preset_defaults.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://github.com/openstreetmap/id-tagging-schema/raw/main/schemas/preset_defaults.json",
    "title": "Default presets",
    "description": "Directory of the IDs of the presets or categories to be shown in the default list for each geometry type.",
    "type": "object",
    "properties": {
        "point": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "string"
            }
        },
        "vertex": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "string"
            }
        },
        "line": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "string"
            }
        },
        "area": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "string"
            }
        },
        "relation": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "string"
            }
        }
    },
    "required": [
        "point",
        "vertex",
        "line",
        "area",
        "relation"
    ],
    "additionalProperties": false
}

=== openstreetmap/id-tagging-schema/dist/preset_defaults.json
{
    "area": [
        "category-landuse",
        "category-building",
        "category-water",
        "category-natural",
        "leisure/park",
        "amenity/hospital",
        "amenity/place_of_worship",
        "amenity/cafe",
        "amenity/restaurant",
        "area"
    ],
    "line": [
        "category-road_major",
        "category-road_minor",
        "category-rail",
        "category-path",
        "category-waterway",
        "category-barrier",
        "category-natural",
        "category-utility",
        "line"
    ],
    "point": [
        "category-natural",
        "leisure/park",
        "amenity/hospital",
        "amenity/place_of_worship",
        "amenity/cafe",
        "amenity/restaurant",
        "amenity/fast_food",
        "amenity/bar",
        "amenity/bank",
        "shop/supermarket",
        "category-advertising",
        "point"
    ],
    "vertex": [
        "highway/crossing/traffic_signals",
        "highway/crossing/uncontrolled",
        "highway/crossing/unmarked",
        "railway/level_crossing",
        "highway/traffic_signals",
        "highway/turning_circle",
        "highway/turning_loop",
        "traffic_calming",
        "highway/mini_roundabout",
        "highway/motorway_junction",
        "point"
    ],
    "relation": [
        "category-route",
        "category-restriction",
        "public_transport/stop_area",
        "type/boundary",
        "type/waterway",
        "type/multipolygon",
        "type/enforcement",
        "type/site",
        "relation"
    ]
}
