=== openstreetmap/id-tagging-schema/schemas/preset.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://github.com/openstreetmap/id-tagging-schema/raw/main/schemas/preset.json",
    "title": "Preset",
    "description": "Associates an icon, form fields, and other UI with a set of OSM tags",
    "type": "object",
    "properties": {
        "name": {
            "description": "The English name for the feature. A preset can reference the label of another by using that preset's identifier contained in brackets (e.g. {preset}), in which case also the preset's aliases and terms will also be referenced from that preset.",
            "type": "string",
            "minLength": 1
        },
        "geometry": {
            "description": "Valid geometry types for the feature, in order of preference",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "string",
                "enum": [
                    "point",
                    "vertex",
                    "line",
                    "area",
                    "relation"
                ]
            }
        },
        "tags": {
            "description": "Tags that must be present for the preset to match",
            "type": "object",
            "additionalProperties": {
                "type": "string",
                "minLength": 1
            }
        },
        "addTags": {
            "description": "Tags that are added when changing to the preset (default is the same value as 'tags')",
            "type": "object",
            "additionalProperties": {
                "type": "string",
                "minLength": 1
            }
        },
        "removeTags": {
            "description": "Tags that are removed when changing to another preset (default is the same value as 'addTags' which in turn defaults to 'tags'). Editors may additionally remove other tags such as tags of the old preset's fields.",
            "type": "object",
            "additionalProperties": {
                "type": "string",
                "minLength": 1
            }
        },
        "fields": {
            "description": "Default form fields that are displayed for the preset. A preset can reference the fields of another by using that preset's identifier contained in brackets as one of the entries, like {preset}.",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "string",
                "minLength": 1
            }
        },
        "moreFields": {
            "description": "Additional form fields that can be attached with the 'Add field' dropdown. A preset can reference the \"moreFields\" of another by using that preset's identifier contained in brackets as one of the entries, like {preset}.",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "string",
                "minLength": 1
            }
        },
        "icon": {
            "description": "Name of the icon that represents this preset, or a cross-reference `{presets/<preset-id>}`.",
            "type": "string",
            "minLength": 1
        },
        "imageURL": {
            "description": "The URL of a remote image that is more specific than 'icon'",
            "type": "string",
            "minLength": 1
        },
        "terms": {
            "description": "English search terms or related keywords",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "string",
                "minLength": 1
            }
        },
        "aliases": {
            "description": "Display-ready English synonyms for the `name`",
            "type": "array",
            "minItems": 1,
            "uniqueItems": true,
            "items": {
                "type": "string",
                "minLength": 1
            }
        },
        "searchable": {
            "description": "Whether or not the preset will be suggested via search",
            "type": "boolean",
            "default": true
        },
        "matchScore": {
            "description": "The quality score this preset will receive when being compared with other matches (higher is better)",
            "type": "number",
            "default": 1.0
        },
        "reference": {
            "description": "Taginfo documentation parameters (to be used when a preset manages multiple tags)",
            "type": "object",
            "properties": {
                "key": {
                    "description": "For documentation of a key",
                    "type": "string",
                    "minLength": 1
                },
                "value": {
                    "description": "For documentation of a tag (key and value)",
                    "type": "string",
                    "minLength": 1
                }
            },
            "additionalProperties": false,
            "required": [
                "key"
            ]
        },
        "replacement": {
            "description": "The ID of a preset that is preferable to this one",
            "type": "string",
            "minLength": 1
        },
        "locationSet": {
            "description": "An object specifying the IDs of regions where this preset is or isn't valid. See: https://github.com/ideditor/location-conflation (but \"include\": [\"Planet\"] may and should be omitted)",
            "type": "object",
            "properties": {
                "include": {
                    "type": "array",
                    "uniqueItems": true,
                    "items": {
                        "type": "string",
                        "minLength": 1
                    }
                },
                "exclude": {
                    "type": "array",
                    "uniqueItems": true,
                    "items": {
                        "type": "string",
                        "minLength": 1
                    }
                }
            },
            "minProperties": 1,
            "additionalProperties": false
        },
        "locationSetCrossReference": {
            "type": "string",
            "minLength": 1,
            "pattern": "^\\{(presets|fields)\\/.+\\}$",
            "description": "An string referencing another preset or field which has a locationSet"
        },
        "related": {
            "description": "Hints about related presets that are related to this one, can be optionally used for a context-aware handling",
            "type": "object",
            "properties": {
                "expectedVertices": {
                    "description": "A list of preset IDs expected to be used as a vertex of this preset, when this preset is used on a line or area. List is ordered, starting from ones more likely to be selected by mapper.",
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                        "type": "string",
                        "minLength": 1
                    }
                }
            },
            "minProperties": 1,
            "additionalProperties": false
        },
        "relation": {
            "$ref": "#/$defs/RelationSchema"
        },
        "relationCrossReference": {
            "description": "A preset can reference the relation schema from another preset, instead of defining the same schema again. If present, then the `relation` property must not appear.",
            "type": "string",
            "minLength": 1,
            "pattern": "^\\{.+\\}$"
        }
    },
    "additionalProperties": false,
    "required": [
        "name",
        "geometry",
        "tags"
    ],
    "$defs": {
        "RelationSchema": {
            "type": "object",
            "properties": {
                "reference": {
                    "type": "string",
                    "minLength": 1,
                    "description": "The “permanent relation type ID”, this must match the value of https://osm.wiki/Property:P41 in the OSM wiki’s wikibase system."
                },
                "allowDuplicateMembers": {
                    "type": "boolean",
                    "description": "Set to `true` if the relation can contain the same member multiple times."
                },
                "role_labels": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "minProperties": 1,
                    "description": "The labels for each role, in the default language. The role and the label can both be empty strings."
                },
                "members": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "role": {
                                "type": "string",
                                "description": "The relation role. An empty string is allowed."
                            },
                            "geometry": {
                                "type": "array",
                                "minItems": 1,
                                "uniqueItems": true,
                                "items": {
                                    "$ref": "./field.json#/$defs/Geometry"
                                },
                                "description": "If not specified, any geometry is allowed"
                            },
                            "matchTags": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "additionalProperties": {
                                        "type": "string",
                                        "minLength": 1
                                    },
                                    "minProperties": 1
                                },
                                "minItems": 1,
                                "examples": [
                                    [
                                        {
                                            "a": "1",
                                            "b": "2"
                                        }
                                    ],
                                    [
                                        {
                                            "a": "1"
                                        },
                                        {
                                            "b": "2"
                                        }
                                    ]
                                ],
                                "description": "`*` can be used as a tag value. If the object has multiple tags, then all tags must match (logical AND). If multiple array items are specified, only 1 needs to match (logical OR). If this property is not specified, then any tags are allowed."
                            },
                            "min": {
                                "type": "integer",
                                "description": "If unspecified, there is no minimum for how many times this role can appear in the relation"
                            },
                            "max": {
                                "type": "integer",
                                "description": "If unspecified, there is no maximum for how many times this role can appear in the relation"
                            }
                        },
                        "required": [
                            "role"
                        ],
                        "additionalProperties": false
                    }
                }
            },
            "required": [
                "reference",
                "allowDuplicateMembers",
                "role_labels",
                "members"
            ],
            "additionalProperties": false
        }
    }
}

=== openstreetmap/id-tagging-schema/data/presets/amenity/waste/sharps.json
{
    "icon": "fas-syringe",
    "fields": [
        "{amenity/waste_basket}"
    ],
    "moreFields": [
        "{amenity/waste_basket}"
    ],
    "geometry": [
        "point",
        "vertex"
    ],
    "tags": {
        "amenity": "waste_basket",
        "waste": "sharps"
    },
    "reference": {
        "key": "waste",
        "value": "sharps"
    },
    "terms": [
        "needle",
        "syringe"
    ],
    "name": "Sharps Container"
}

=== openstreetmap/id-tagging-schema/data/presets/amenity/grave_yard.json
{
    "icon": "maki-cemetery",
    "fields": [
        "religion",
        "address"
    ],
    "moreFields": [
        "{@templates/contact}",
        "gnis/feature_id-US",
        "operator"
    ],
    "geometry": [
        "point",
        "area"
    ],
    "tags": {
        "amenity": "grave_yard"
    },
    "terms": [
        "burial ground",
        "cemetary",
        "cemetery",
        "churchyard",
        "columbarium",
        "grave yard",
        "graveyard",
        "graveyards",
        "mausoleum",
        "tomb"
    ],
    "name": "Graveyard"
}

=== openstreetmap/id-tagging-schema/data/presets/type/boundary/administrative.json
{
    "icon": "iD-boundary",
    "fields": [
        "name",
        "admin_level"
    ],
    "moreFields": [
        "gnis/feature_id-US"
    ],
    "geometry": [
        "relation"
    ],
    "tags": {
        "type": "boundary",
        "boundary": "administrative"
    },
    "reference": {
        "key": "boundary",
        "value": "administrative"
    },
    "name": "Administrative Boundary",
    "relation": {
        "reference": "boundary",
        "allowDuplicateMembers": false,
        "role_labels": {
            "inner": "{area.role_labels.inner}",
            "outer": "{area.role_labels.outer}",
            "label": "Label",
            "admin_centre": "Capital / Seat"
        },
        "members": [
            {
                "role": "outer",
                "geometry": [
                    "line",
                    "area"
                ],
                "min": 1
            },
            {
                "role": "inner",
                "geometry": [
                    "line",
                    "area"
                ]
            },
            {
                "role": "label",
                "geometry": [
                    "point",
                    "vertex"
                ],
                "matchTags": [
                    {
                        "place": "*"
                    }
                ],
                "max": 1
            },
            {
                "role": "admin_centre",
                "geometry": [
                    "point",
                    "vertex"
                ],
                "matchTags": [
                    {
                        "place": "*"
                    }
                ],
                "max": 1
            }
        ]
    }
}

=== openstreetmap/id-tagging-schema/data/presets/landuse/recreation_ground.json
{
    "icon": "maki-pitch",
    "geometry": [
        "area"
    ],
    "fields": [
        "name"
    ],
    "moreFields": [
        "{@templates/contact}",
        "address"
    ],
    "tags": {
        "landuse": "recreation_ground"
    },
    "terms": [
        "playing fields",
        "recreation grounds"
    ],
    "name": "Recreation Ground"
}

=== openstreetmap/id-tagging-schema/data/presets/natural/water.json
{
    "icon": "maki-water",
    "fields": [
        "name",
        "water",
        "intermittent"
    ],
    "moreFields": [
        "fishing",
        "gnis/feature_id-US",
        "salt",
        "tidal"
    ],
    "geometry": [
        "area"
    ],
    "tags": {
        "natural": "water"
    },
    "name": "Water"
}

=== openstreetmap/id-tagging-schema/data/presets/shop/appliance.json
{
    "icon": "temaki-laundry",
    "geometry": [
        "point",
        "area"
    ],
    "terms": [
        "air conditioner",
        "appliance",
        "appliance stores",
        "dishwasher",
        "dryer",
        "freezer",
        "fridge",
        "grill",
        "kitchen",
        "oven",
        "refrigerator",
        "stove",
        "washer",
        "washing machine",
        "white goods"
    ],
    "fields": [
        "{shop}"
    ],
    "moreFields": [
        "{shop}"
    ],
    "tags": {
        "shop": "appliance"
    },
    "name": "Appliance Store"
}

=== openstreetmap/id-tagging-schema/data/presets/shop/estate_agent.json
{
    "icon": "temaki-real_estate_agency",
    "fields": [
        "{shop}"
    ],
    "moreFields": [
        "{shop}"
    ],
    "geometry": [
        "point",
        "area"
    ],
    "tags": {
        "shop": "estate_agent"
    },
    "terms": [
        "estate agent",
        "real estate",
        "real estate agent",
        "real estate office"
    ],
    "name": "Real Estate Agency"
}

=== openstreetmap/id-tagging-schema/data/presets/amenity/charging_station/bicycle.json
{
    "icon": "fas-charging-station",
    "fields": [
        "{amenity/charging_station}"
    ],
    "moreFields": [
        "{amenity/charging_station}"
    ],
    "geometry": [
        "point",
        "vertex",
        "area"
    ],
    "tags": {
        "amenity": "charging_station",
        "bicycle": "yes"    
    },
    "terms": [
        "EV",
        "Electric Bicycle",
        "Pedelec Charging",
        "E-Bike"
    ],
    "reference": {
        "key": "amenity",
        "value": "charging_station"
    },
    "name": "Charging Station for Electric Bicycles"
}
